# Generated by Django 4.2.7 on 2024-02-17 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lang',
            new_name='Language',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='lang',
            new_name='language',
        ),
    ]
